import express from 'express';
import { protect, admin } from '../middleware/auth.js';
import Course from '../models/Course.js';
import DocumentUpload from '../models/DocumentUpload.js';
import axios from 'axios';
import FormData from 'form-data';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { getContextForStep } from '../services/documentProcessor.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const router = express.Router();

// Store generation progress in memory
const generationSessions = {};

// Helper function to normalize file path
const normalizeFilePath = (filePath) => {
  return filePath.replace(/\\/g, '/');
};

const buildGenerationFormData = (document, step, extras = {}) => {
  if (!document.extractedText?.trim()) {
    throw new Error('Document must be processed before generation. Please process the document first.');
  }

  const formData = new FormData();
  const documentContext = getContextForStep(document.extractedText, step, {
    unitIndex: extras.unitIndex ?? 0,
    totalUnits: extras.totalUnits ?? 1
  });

  formData.append('documentText', documentContext);
  formData.append('step', step);

  if (extras.sessionId) formData.append('sessionId', extras.sessionId);
  if (extras.overview !== undefined) {
    const overviewValue = Array.isArray(extras.overview)
      ? JSON.stringify(extras.overview)
      : extras.overview;
    formData.append('overview', overviewValue);
  }
  if (extras.unitIndex !== undefined) formData.append('unitIndex', String(extras.unitIndex));
  if (extras.unitTitle) formData.append('unitTitle', extras.unitTitle);
  if (extras.unitDescription !== undefined) {
    formData.append('unitDescription', extras.unitDescription || '');
  }
  if (extras.feedbackInstructions) {
    formData.append('feedbackInstructions', extras.feedbackInstructions);
  }

  // Attach file as fallback when AI service needs to re-extract
  let filePath = document.filePath;
  if (!fs.existsSync(filePath)) {
    const absolutePath = path.join(process.cwd(), filePath);
    if (fs.existsSync(absolutePath)) {
      filePath = absolutePath;
    }
  }
  if (fs.existsSync(filePath)) {
    formData.append('file', fs.createReadStream(normalizeFilePath(filePath)));
  }

  return formData;
};

// Helper function to check if Python service is running
const checkPythonService = async () => {
  try {
    await axios.get('http://localhost:8000/health', { timeout: 2000 });
    return true;
  } catch (error) {
    console.error('Python service check failed:', error.message);
    return false;
  }
};

// Helper function to get or create generation session
const getOrCreateGenerationSession = async (documentId, userId) => {
  const document = await DocumentUpload.findById(documentId);

  if (!document) {
    throw new Error('Document not found');
  }

  // Check if session exists in memory
  if (document.generationSessionId && generationSessions[document.generationSessionId]) {
    const session = generationSessions[document.generationSessionId];
    if (session.userId.toString() !== userId.toString()) {
      throw new Error('This document is being generated by another user');
    }
    return session;
  }

  // Create new session
  const sessionId = Date.now().toString();

  // Convert stored unitContents from object to array
  let unitContentsArray = [];
  if (document.generationProgress?.unitContents) {
    if (typeof document.generationProgress.unitContents === 'object' && !Array.isArray(document.generationProgress.unitContents)) {
      unitContentsArray = Object.values(document.generationProgress.unitContents);
    } else if (Array.isArray(document.generationProgress.unitContents)) {
      unitContentsArray = document.generationProgress.unitContents;
    }
  }

  const newSession = {
    sessionId,
    documentId: document._id,
    documentPath: document.filePath,
    documentName: document.originalName,
    userId,
    step: document.generationStatus || 'overview',
    data: {
      overview: document.generationProgress?.overview || null,
      units: document.generationProgress?.units || [],
      unitContents: unitContentsArray,
      completedUnits: document.generationProgress?.completedUnits || []
    },
    createdAt: new Date()
  };

  generationSessions[sessionId] = newSession;

  // Update document with session info
  document.generationSessionId = sessionId;
  if (document.generationStatus === 'not_started') {
    document.generationStatus = 'overview_generated';
  }
  await document.save();

  return newSession;
};

// Helper functions
const calculateTotalDuration = (unitContents) => {
  if (!unitContents || !Array.isArray(unitContents)) return 0;
  return unitContents.reduce((total, unit) => {
    return total + calculateUnitDuration(unit);
  }, 0);
};

const calculateTotalXP = (unitContents) => {
  if (!unitContents || !Array.isArray(unitContents)) return 0;
  return unitContents.reduce((total, unit) => {
    return total + calculateUnitXP(unit);
  }, 0);
};

const calculateUnitDuration = (unitContent) => {
  if (!unitContent || !unitContent.screens) return 30;
  return unitContent.screens.length * 2;
};

const calculateUnitXP = (unitContent) => {
  if (!unitContent || !unitContent.screens) return 25;

  let totalXP = 0;
  unitContent.screens.forEach(screen => {
    if (screen.type === 'concept-check' && screen.questions) {
      screen.questions.forEach(q => {
        totalXP += q.xp || 5;
      });
    } else if (screen.type === 'coding') {
      totalXP += screen.xp || 10;
    }
  });
  return totalXP || 25;
};

const extractKeyTakeaways = (unitContent) => {
  if (!unitContent || !unitContent.screens) {
    return [`Master ${unitContent?.title || 'this unit'}`];
  }

  const takeawaysScreen = unitContent.screens.find(
    screen => screen.title?.toLowerCase().includes('takeaway')
  );

  if (takeawaysScreen?.description) {
    const lines = takeawaysScreen.description.split('\n');
    const takeaways = lines
      .filter(line => line.trim().startsWith('•') || line.trim().startsWith('-') || line.trim().match(/^\d+\./))
      .map(line => line.replace(/^[•\- \d\.]+/, '').trim())
      .filter(t => t.length > 0);

    if (takeaways.length > 0) return takeaways;
  }

  return [
    `Understand core concepts of ${unitContent?.title || 'this unit'}`,
    'Apply the knowledge in practical scenarios',
    'Complete the exercises to reinforce learning'
  ];
};

// Debug endpoint to check sessions
router.get('/debug/sessions', protect, admin, (req, res) => {
  const sessions = Object.keys(generationSessions).map(sessionId => ({
    sessionId,
    documentId: generationSessions[sessionId].documentId,
    step: generationSessions[sessionId].step,
    hasOverview: !!generationSessions[sessionId].data?.overview,
    unitsCount: generationSessions[sessionId].data?.units?.length || 0,
    completedUnits: generationSessions[sessionId].data?.completedUnits?.length || 0,
    createdAt: generationSessions[sessionId].createdAt
  }));
  res.json({ sessions, total: sessions.length });
});

router.post('/step/recover/:documentId', protect, admin, async (req, res) => {
  try {
    const document = await DocumentUpload.findById(req.params.documentId);
    if (!document) {
      return res.status(404).json({ message: 'Document not found' });
    }

    // Create new session from document data
    const sessionId = Date.now().toString();
    const newSession = {
      sessionId,
      documentId: document._id,
      documentPath: document.filePath,
      documentName: document.originalName,
      userId: req.user._id,
      step: document.generationStatus || 'overview',
      data: {
        overview: document.generationProgress?.overview || null,
        units: document.generationProgress?.units || [],
        unitContents: document.generationProgress?.unitContents || [],
        completedUnits: document.generationProgress?.completedUnits || []
      },
      createdAt: new Date()
    };

    generationSessions[sessionId] = newSession;
    document.generationSessionId = sessionId;
    await document.save();

    res.json({ sessionId, message: 'Session recovered' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Step 1: Generate Overview
router.post('/step/overview/:documentId', protect, admin, async (req, res) => {
  try {
    const document = await DocumentUpload.findById(req.params.documentId);
    if (!document) {
      return res.status(404).json({ message: 'Document not found' });
    }

    // Check if overview already exists
    if (document.generationProgress?.overview) {
      const session = await getOrCreateGenerationSession(req.params.documentId, req.user._id);
      return res.json({
        sessionId: session.sessionId,
        overview: document.generationProgress.overview,
        message: 'Resuming from existing overview'
      });
    }

    // Check if document is already completed
    if (document.generationStatus === 'completed') {
      return res.status(400).json({
        message: 'A course has already been generated from this document.'
      });
    }

    const isPythonRunning = await checkPythonService();
    if (!isPythonRunning) {
      return res.status(503).json({
        message: 'AI service is not running. Please start the Python server on port 8000.'
      });
    }

    if (!document.extractedText?.trim()) {
      return res.status(400).json({
        message: 'Document has not been processed yet. Please process the document before generating a course.'
      });
    }

    console.log('Sending chunked document context to Python service:', {
      documentId: document._id,
      textLength: document.extractedText.length,
      chunkCount: document.chunkCount || 'unknown'
    });

    // IMPORTANT: Create session FIRST before calling Python
    const session = await getOrCreateGenerationSession(req.params.documentId, req.user._id);

    const formData = buildGenerationFormData(document, 'overview', {
      sessionId: session.sessionId
    });

    const pythonResponse = await axios.post(
      'http://localhost:8000/generate-step',
      formData,
      {
        headers: {
          ...formData.getHeaders(),
          'Accept': 'application/json'
        },
        timeout: 60000,
        maxContentLength: Infinity,
        maxBodyLength: Infinity
      }
    );

    // ✅ FIX: Check if response exists
    if (!pythonResponse || !pythonResponse.data) {
      return res.status(500).json({ message: 'No response from AI service' });
    }

    // ✅ FIX: Check for error in response
    if (pythonResponse.data.error) {
      return res.status(500).json({ message: pythonResponse.data.error });
    }

    // ✅ FIX: Check if overview exists
    if (!pythonResponse.data.overview) {
      console.error('Python response missing overview:', pythonResponse.data);
      return res.status(500).json({ message: 'Invalid response from AI service: missing overview' });
    }

    // Save overview to document
    document.generationProgress.overview = pythonResponse.data.overview;
    document.generationProgress.category = pythonResponse.data.category || 'General';
    document.generationStatus = 'overview_generated';
    document.generationProgress.lastUpdated = new Date();
    await document.save();

    session.data.overview = pythonResponse.data.overview;
    session.data.category = pythonResponse.data.category || 'General';

    res.json({
      sessionId: session.sessionId,
      overview: pythonResponse.data.overview,
      message: 'Overview generated successfully'
    });

  } catch (error) {
    console.error('Overview generation error:', error);
    res.status(500).json({ message: error.message });
  }
});

// Step 2: Generate Units
router.post('/step/units/:sessionId', protect, admin, async (req, res) => {
  try {
    const { sessionId } = req.params;
    const { overview } = req.body;

    let session = generationSessions[sessionId];
    if (!session) {
      return res.status(404).json({ message: 'Session not found or expired. Please restart the generation process.' });
    }

    const document = await DocumentUpload.findById(session.documentId);

    // Check if units already exist
    if (document.generationProgress?.units && document.generationProgress.units.length > 0) {
      session.data.units = document.generationProgress.units;
      return res.json({
        sessionId,
        units: document.generationProgress.units,
        message: 'Resuming from existing units'
      });
    }

    // Check if already completed
    if (document.generationStatus === 'completed') {
      return res.status(400).json({
        message: 'This document has already been processed completely.'
      });
    }

    session.data.overview = overview;

    const formData = buildGenerationFormData(document, 'units', {
      sessionId,
      overview
    });

    console.log('Sending units request for session:', sessionId);

    const pythonResponse = await axios.post(
      'http://localhost:8000/generate-step',
      formData,
      {
        headers: formData.getHeaders(),
        timeout: 60000
      }
    );

    if (pythonResponse.data.error) {
      return res.status(500).json({ message: pythonResponse.data.error });
    }

    // Store units
    session.data.units = pythonResponse.data.units;
    document.generationProgress.units = pythonResponse.data.units;
    document.generationStatus = 'units_generated';
    document.generationProgress.lastUpdated = new Date();
    await document.save();

    session.data.unitContents = new Array(pythonResponse.data.units.length).fill(null);

    console.log(`Generated ${pythonResponse.data.units.length} units for session ${sessionId}`);

    res.json({
      sessionId,
      units: pythonResponse.data.units,
      message: 'Units generated successfully'
    });

  } catch (error) {
    console.error('Units generation error:', error.message);
    res.status(500).json({ message: error.message });
  }
});

// Step 3: Generate Unit Content
router.post('/step/unit-content/:sessionId/:unitIndex', protect, admin, async (req, res) => {
  try {
    const { sessionId, unitIndex } = req.params;
    const { unitTitle, unitDescription } = req.body;
    const index = parseInt(unitIndex);

    const session = generationSessions[sessionId];
    if (!session) {
      return res.status(404).json({ message: 'Session not found or expired. Please restart the generation process.' });
    }

    const document = await DocumentUpload.findById(session.documentId);

    // Check if this unit was already generated
    const completedUnits = document.generationProgress?.completedUnits || [];
    if (completedUnits.includes(index)) {
      const existingUnit = document.generationProgress.unitContents?.[index.toString()];
      if (existingUnit) {
        return res.json({
          sessionId,
          unit: existingUnit,
          meta: { source: 'resumed', message: 'Unit already generated' },
          message: `Unit ${index + 1} already generated`
        });
      }
    }

    if (document.generationStatus === 'completed') {
      return res.status(400).json({
        message: 'This document has already been fully processed.'
      });
    }

    if (!session.data.units || session.data.units.length === 0) {
      return res.status(400).json({ message: 'No units found. Please generate units first.' });
    }

    if (!document.extractedText?.trim()) {
      return res.status(400).json({
        message: 'Document has not been processed yet. Please process the document before generating unit content.'
      });
    }

    document.generationStatus = 'unit_content_generating';
    await document.save();

    const formData = buildGenerationFormData(document, 'unit-content', {
      sessionId,
      unitIndex: index,
      totalUnits: session.data.units.length,
      unitTitle,
      unitDescription,
      overview: session.data.overview,
      feedbackInstructions: req.body.feedbackInstructions
    });

    console.log(`Generating content for unit ${index + 1} in session ${sessionId}`);

    const pythonResponse = await axios.post(
      'http://localhost:8000/generate-step',
      formData,
      {
        headers: formData.getHeaders(),
        timeout: 90000
      }
    );

    if (pythonResponse.data.error) {
      return res.status(500).json({ message: pythonResponse.data.error });
    }

    // Store unit content
    if (!session.data.unitContents) {
      session.data.unitContents = [];
    }
    session.data.unitContents[index] = pythonResponse.data.unit;

    // Save to document
    if (!document.generationProgress.unitContents) {
      document.generationProgress.unitContents = {};
    }
    document.generationProgress.unitContents[index.toString()] = pythonResponse.data.unit;

    if (!completedUnits.includes(index)) {
      completedUnits.push(index);
      document.generationProgress.completedUnits = completedUnits;
    }

    document.generationProgress.lastUpdated = new Date();
    await document.save();

    console.log(`Unit content generated successfully for unit ${index + 1} in session ${sessionId}`);

    res.json({
      sessionId,
      unit: pythonResponse.data.unit,
      meta: pythonResponse.data.meta || null,
      message: `Unit ${index + 1} content generated`
    });

  } catch (error) {
    console.error('Unit content generation error:', error.message);
    res.status(500).json({ message: error.message });
  }
});

// Step 4: Save Complete Course (Final save)
router.post('/step/save/:sessionId', protect, admin, async (req, res) => {
  try {
    const { sessionId } = req.params;
    const { title, category, difficulty } = req.body;

    const session = generationSessions[sessionId];
    if (!session) {
      return res.status(404).json({ message: 'Session not found or expired' });
    }

    if (!session.data.overview) {
      return res.status(400).json({ message: 'Missing course overview' });
    }
    if (!session.data.units || !Array.isArray(session.data.units)) {
      return res.status(400).json({ message: 'Missing course units' });
    }

    const courseData = {
      title: title || session.documentName.replace(/\.[^/.]+$/, ""),
      category: session.data.category || 'General',
      difficulty: difficulty || 'Beginner',
      totalDuration: calculateTotalDuration(session.data.unitContents),
      totalXP: calculateTotalXP(session.data.unitContents),
      learningObjectives: Array.isArray(session.data.overview) ? session.data.overview : [session.data.overview],
      units: session.data.units?.map((unit, uIdx) => {
        const unitContent = session.data.unitContents?.[uIdx];
        return {
          unitId: `unit-${uIdx + 1}`,
          title: unit.title,
          duration: calculateUnitDuration(unitContent),
          totalXP: calculateUnitXP(unitContent),
          displayMessage: unit.description || `Ready to master ${unit.title}? Start now!`,
          screens: unitContent?.screens?.map((screen, lIdx) => {
            const screenObj = {
              screenId: `screen-${uIdx + 1}-${lIdx + 1}`,
              title: screen.title,
              description: screen.description || screen.content || '',
              type: screen.type || 'content',
              xp: screen.xp || 0
            };

            if (screen.type === 'concept-check' && screen.questions) {
              screenObj.questions = screen.questions.map((q, qIdx) => ({
                questionId: `q-${uIdx + 1}-${lIdx + 1}-${qIdx + 1}`,
                type: q.type || 'mcq',
                question: q.question,
                options: q.options || [],
                correctAnswer: q.correctAnswer,
                explanation: q.explanation || '',
                xp: q.xp || 5
              }));
            } else if (screen.type === 'coding') {
              screenObj.codeExample = screen.codeExample || '';
              screenObj.question = screen.question || '';
              screenObj.correctAnswer = screen.correctAnswer || '';
              screenObj.explanation = screen.explanation || '';
            }

            return screenObj;
          }) || [],
          keyTakeaways: extractKeyTakeaways(unitContent)
        };
      }) || [],
      status: 'draft',
      generatedFrom: session.documentId,
      generatedBy: req.user._id,
      aiGenerated: true
    };

    let course;
    if (session.draftCourseId) {
      course = await Course.findByIdAndUpdate(session.draftCourseId, courseData, {
        new: true,
        runValidators: true
      });
    } else {
      course = new Course(courseData);
      await course.save();
    }

    // Mark document as completed
    const document = await DocumentUpload.findById(session.documentId);
    document.generationStatus = 'completed';
    document.generatedCourseId = course._id;
    document.generationProgress.lastUpdated = new Date();
    await document.save();

    // Clean up session
    delete generationSessions[sessionId];

    res.json({
      message: 'Course saved successfully',
      courseId: course._id
    });

  } catch (error) {
    console.error('Save course error:', error.message);
    res.status(500).json({ message: error.message });
  }
});

// Step 4a: Save progress (auto-save) - WITH SESSION RECOVERY
router.post('/step/save-progress/:sessionId', protect, admin, async (req, res) => {
  try {
    const { sessionId } = req.params;
    const { title, category, difficulty } = req.body;

    let session = generationSessions[sessionId];

    // If session not found in memory, try to recover from database
    if (!session) {
      console.log(`Session ${sessionId} not found in memory, attempting to recover from database...`);

      // Find document by sessionId
      const document = await DocumentUpload.findOne({ generationSessionId: sessionId });
      if (!document) {
        return res.status(404).json({ message: 'Session not found and could not recover from database' });
      }

      // Recreate session from document data
      let unitContentsArray = [];
      if (document.generationProgress?.unitContents) {
        if (typeof document.generationProgress.unitContents === 'object' && !Array.isArray(document.generationProgress.unitContents)) {
          unitContentsArray = Object.values(document.generationProgress.unitContents);
        } else if (Array.isArray(document.generationProgress.unitContents)) {
          unitContentsArray = document.generationProgress.unitContents;
        }
      }

      session = {
        sessionId,
        documentId: document._id,
        documentPath: document.filePath,
        documentName: document.originalName,
        userId: req.user._id,
        step: document.generationStatus || 'overview',
        data: {
          overview: document.generationProgress?.overview || null,
          units: document.generationProgress?.units || [],
          unitContents: unitContentsArray,
          completedUnits: document.generationProgress?.completedUnits || []
        },
        createdAt: new Date()
      };

      generationSessions[sessionId] = session;
      console.log(`Session ${sessionId} recovered successfully`);
    }

    const courseData = {
      title: title || session.documentName.replace(/\.[^/.]+$/, ""),
      category: category || 'General',
      difficulty: difficulty || 'Beginner',
      totalDuration: calculateTotalDuration(session.data.unitContents),
      totalXP: calculateTotalXP(session.data.unitContents),
      learningObjectives: session.data.overview
        ? (Array.isArray(session.data.overview) ? session.data.overview : [session.data.overview])
        : [],
      units: session.data.units?.map((unit, uIdx) => {
        const unitContent = session.data.unitContents?.[uIdx];
        return {
          unitId: `unit-${uIdx + 1}`,
          title: unit.title,
          duration: calculateUnitDuration(unitContent),
          totalXP: calculateUnitXP(unitContent),
          displayMessage: unit.description || `Ready to master ${unit.title}? Start now!`,
          screens: unitContent?.screens?.map((screen, lIdx) => {
            const screenObj = {
              screenId: `screen-${uIdx + 1}-${lIdx + 1}`,
              title: screen.title,
              description: screen.description || screen.content || '',
              type: screen.type || 'content',
              xp: screen.xp || 0
            };

            if (screen.type === 'concept-check' && screen.questions) {
              screenObj.questions = screen.questions.map((q, qIdx) => ({
                questionId: `q-${uIdx + 1}-${lIdx + 1}-${qIdx + 1}`,
                type: q.type || 'mcq',
                question: q.question,
                options: q.options || [],
                correctAnswer: q.correctAnswer,
                explanation: q.explanation || '',
                xp: q.xp || 5
              }));
            } else if (screen.type === 'coding') {
              screenObj.codeExample = screen.codeExample || '';
              screenObj.question = screen.question || '';
              screenObj.correctAnswer = screen.correctAnswer || '';
              screenObj.explanation = screen.explanation || '';
            }

            return screenObj;
          }) || [],
          keyTakeaways: extractKeyTakeaways(unitContent)
        };
      }) || [],
      status: 'draft',
      generatedFrom: session.documentId,
      generatedBy: req.user._id,
      aiGenerated: true
    };

    let draft;
    if (session.draftCourseId) {
      draft = await Course.findByIdAndUpdate(session.draftCourseId, courseData, {
        new: true,
        runValidators: true
      });
    } else {
      draft = new Course(courseData);
      await draft.save();
      session.draftCourseId = draft._id;
    }

    // Update the lastUpdated timestamp
    const document = await DocumentUpload.findById(session.documentId);
    if (document) {
      document.generationProgress.lastUpdated = new Date();
      await document.save();
    }

    console.log(`Progress saved successfully for session ${sessionId}, courseId: ${draft._id}`);

    res.json({
      message: 'Progress saved',
      courseId: draft._id
    });
  } catch (error) {
    console.error('Save progress error:', error.message);
    console.error('Stack:', error.stack);
    res.status(500).json({ message: error.message });
  }
});

// Get all drafts
router.get('/drafts', protect, admin, async (req, res) => {
  try {
    const drafts = await Course.find({ status: 'draft' })
      .populate('generatedFrom', 'originalName')
      .populate('generatedBy', 'username')
      .sort('-createdAt');
    res.json(drafts);
  } catch (error) {
    console.error('Get drafts error:', error.message);
    res.status(500).json({ message: error.message });
  }
});

// Get single draft 
router.get('/drafts/:courseId', protect, admin, async (req, res) => {
  try {
    const course = await Course.findById(req.params.courseId)
      .populate('generatedFrom', 'originalName')
      .populate('generatedBy', 'username');

    if (!course) {
      return res.status(404).json({ message: 'Course not found' });
    }

    res.json(course);
  } catch (error) {
    console.error('Get course error:', error.message);
    res.status(500).json({ message: error.message });
  }
});

// Update draft
router.put('/drafts/:courseId', protect, admin, async (req, res) => {
  try {
    const draft = await Course.findOneAndUpdate(
      { _id: req.params.courseId, status: 'draft' },
      req.body,
      { new: true, runValidators: true }
    );
    if (!draft) {
      return res.status(404).json({ message: 'Draft not found' });
    }
    res.json(draft);
  } catch (error) {
    console.error('Update draft error:', error.message);
    res.status(500).json({ message: error.message });
  }
});

// Get course for review (works for both draft and published)
router.get('/review/:courseId', protect, admin, async (req, res) => {
  try {
    const course = await Course.findById(req.params.courseId)
      .populate('generatedFrom', 'originalName')
      .populate('generatedBy', 'username');

    if (!course) {
      return res.status(404).json({ message: 'Course not found' });
    }

    res.json(course);
  } catch (error) {
    console.error('Get review course error:', error.message);
    res.status(500).json({ message: error.message });
  }
});

// Publish draft
router.post('/publish/:courseId', protect, admin, async (req, res) => {
  try {
    const course = await Course.findById(req.params.courseId);
    if (!course) {
      return res.status(404).json({ message: 'Course not found' });
    }
    course.status = 'published';
    await course.save();
    res.json({ message: 'Course published successfully' });
  } catch (error) {
    console.error('Publish error:', error.message);
    res.status(500).json({ message: error.message });
  }
});

// Delete draft
router.delete('/drafts/:courseId', protect, admin, async (req, res) => {
  try {
    const result = await Course.findOneAndDelete({ _id: req.params.courseId, status: 'draft' });
    if (!result) {
      return res.status(404).json({ message: 'Draft not found' });
    }
    res.json({ message: 'Draft deleted successfully' });
  } catch (error) {
    console.error('Delete draft error:', error.message);
    res.status(500).json({ message: error.message });
  }
});

// Apply feedback to screen
router.post('/apply-feedback/:courseId', protect, admin, async (req, res) => {
  try {
    const { courseId } = req.params;
    const { unitIndex, screenIndex, feedback, screenContent, unitTitle, screenTitle, screenType } = req.body;

    if (!feedback || feedback.trim() === '') {
      return res.status(400).json({ message: 'Feedback is required' });
    }

    const course = await Course.findById(courseId);
    if (!course) {
      return res.status(404).json({ message: 'Course not found' });
    }

    const document = await DocumentUpload.findById(course.generatedFrom);
    if (!document || !document.extractedText) {
      return res.status(404).json({ message: 'Source document not found' });
    }

    const isPythonRunning = await checkPythonService();
    if (!isPythonRunning) {
      return res.status(503).json({
        message: 'AI service is not running. Please start the Python server on port 8000.'
      });
    }

    const response = await axios.post(
      'http://localhost:8000/apply-feedback',
      {
        feedback: feedback,
        screen_content: screenContent,
        context: document.extractedText.substring(0, 3000),
        unit_title: unitTitle,
        screen_title: screenTitle,
        screen_type: screenType
      },
      {
        headers: {
          'Content-Type': 'application/json'
        },
        timeout: 60000
      }
    );

    if (response.data.error) {
      return res.status(500).json({ message: response.data.error });
    }

    // Update the specific screen in the course
    const updatedCourse = course.toObject();
    if (updatedCourse.units[unitIndex] && updatedCourse.units[unitIndex].screens[screenIndex]) {
      updatedCourse.units[unitIndex].screens[screenIndex] = response.data.modified_screen;
    }

    const savedCourse = await Course.findByIdAndUpdate(courseId, updatedCourse, { new: true });

    res.json({
      message: 'Feedback applied successfully',
      modifiedScreen: response.data.modified_screen,
      course: savedCourse
    });

  } catch (error) {
    console.error('Apply feedback error:', error);
    res.status(500).json({ message: error.message });
  }
});

// Live feedback during generation — proxy to Python /modify-generation
router.post('/modify-generation', protect, admin, async (req, res) => {
  try {
    const { action, payload } = req.body;
    if (!action) {
      return res.status(400).json({ message: 'action is required' });
    }

    const isPythonRunning = await checkPythonService();
    if (!isPythonRunning) {
      return res.status(503).json({ message: 'AI service not running on port 8000' });
    }

    const response = await axios.post(
      'http://localhost:8000/modify-generation',
      { action, payload: payload || {} },
      { headers: { 'Content-Type': 'application/json' }, timeout: 60000 }
    );

    res.json(response.data);
  } catch (error) {
    console.error('modify-generation error:', error.message);
    res.status(500).json({ message: error.response?.data?.detail || error.message });
  }
});

// AI Field Improvement - Generate Suggestion
router.post('/suggest-improvement/:courseId', protect, admin, async (req, res) => {
  try {
    const { fieldType, currentValue, feedback, context } = req.body;

    let prompt = '';
    switch (fieldType) {
      case 'course_title':
        prompt = `Improve this course title: "${currentValue}"
Feedback: ${feedback}
Requirements: Make it engaging, clear, and descriptive. Keep under 60 characters.
Return ONLY the improved title as a JSON string: {"title": "Improved Title"}`;
        break;
      case 'learning_objectives':
        prompt = `Improve these learning objectives based on feedback:
Current: ${Array.isArray(currentValue) ? currentValue.join('\n') : currentValue}
Feedback: ${feedback}
Requirements: Make them specific, measurable, action-oriented. Use Bloom's taxonomy verbs.
Return ONLY a JSON array: ["Objective 1", "Objective 2"]`;
        break;
      case 'unit_title':
        prompt = `Improve this unit title: "${currentValue}"
Course: ${context?.courseTitle || ''}
Feedback: ${feedback}
Requirements: Clear, engaging, under 50 characters.
Return ONLY: {"title": "Improved Title"}`;
        break;
      case 'unit_message':
        prompt = `Improve this welcome message: "${currentValue}"
Unit: ${currentValue}
Feedback: ${feedback}
Requirements: Motivating, clear, under 100 characters.
Return ONLY: {"message": "Improved welcome message"}`;
        break;
      case 'key_takeaways':
        prompt = `Improve these key takeaways:
Current: ${Array.isArray(currentValue) ? currentValue.join('\n') : currentValue}
Feedback: ${feedback}
Requirements: Make them actionable, memorable, 3-5 bullet points.
Return ONLY a JSON array: ["Takeaway 1", "Takeaway 2"]`;
        break;
      case 'screen_description':
        prompt = `Improve this screen content:
${currentValue}
Feedback: ${feedback}
Requirements: Keep the same length, make it clearer, add examples if helpful.
Return ONLY: {"description": "Improved description"}`;
        break;
      default:
        return res.status(400).json({ message: 'Unknown field type' });
    }

    // Call Python AI service
    const pythonResponse = await axios.post(
      'http://localhost:8000/generate-prompt',
      { prompt, response_format: 'json' },
      { timeout: 30000 }
    );

    let suggestion = pythonResponse.data.response;
    try {
      const parsed = JSON.parse(suggestion);
      suggestion = parsed.title || parsed.message || parsed.description || (Array.isArray(parsed) ? parsed : suggestion);
    } catch (e) {
      // Keep as is if not JSON
    }

    res.json({ suggestion });
  } catch (error) {
    console.error('Suggestion error:', error);
    res.status(500).json({ message: error.message });
  }
});

// AI Field Improvement - Apply
router.post('/improve-field/:courseId', protect, admin, async (req, res) => {
  try {
    const { fieldType, currentValue, feedback, context } = req.body;

    let prompt = '';
    switch (fieldType) {
      case 'course_title':
        prompt = `Improve this course title: "${currentValue}"
Feedback: ${feedback}
Return ONLY valid JSON: {"title": "Improved Title"}`;
        break;
      case 'learning_objectives':
        prompt = `Improve these learning objectives:
${Array.isArray(currentValue) ? currentValue.join('\n') : currentValue}
Feedback: ${feedback}
Return ONLY a JSON array of improved objectives.`;
        break;
      case 'unit_title':
        prompt = `Improve this unit title: "${currentValue}"
Feedback: ${feedback}
Return ONLY: {"title": "Improved Title"}`;
        break;
      case 'unit_message':
        prompt = `Improve this message: "${currentValue}"
Feedback: ${feedback}
Return ONLY: {"message": "Improved message"}`;
        break;
      case 'key_takeaways':
        prompt = `Improve these takeaways:
${Array.isArray(currentValue) ? currentValue.join('\n') : currentValue}
Feedback: ${feedback}
Return ONLY a JSON array of improved takeaways.`;
        break;
      case 'screen_description':
        prompt = `Improve this content:
${currentValue}
Feedback: ${feedback}
Return ONLY: {"description": "Improved description"}`;
        break;
      default:
        return res.status(400).json({ message: 'Unknown field type' });
    }

    const pythonResponse = await axios.post(
      'http://localhost:8000/generate-prompt',
      { prompt, response_format: 'json' },
      { timeout: 30000 }
    );

    let result = pythonResponse.data.response;
    try {
      result = JSON.parse(result);
    } catch (e) {
      result = { result };
    }

    res.json({ result });
  } catch (error) {
    console.error('Improve field error:', error);
    res.status(500).json({ message: error.message });
  }
});

// Clean up old sessions (24 hours timeout)
setInterval(() => {
  const oneDayAgo = Date.now() - 24 * 60 * 60 * 1000;
  Object.keys(generationSessions).forEach(sessionId => {
    if (generationSessions[sessionId].createdAt < oneDayAgo) {
      delete generationSessions[sessionId];
      console.log(`Cleaned up expired session: ${sessionId}`);
    }
  });
}, 30 * 60 * 1000);

// reset provider availability periodically
setInterval(async () => {
  try {
    await axios.post('http://localhost:8000/reset-providers', {}, { timeout: 2000 });
  } catch (e) {
    // Ignore - service might be down
  }
}, 60 * 60 * 1000); // Hourly

export default router;